# Generated by Django 6.0.2 on 2026-02-23 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.room')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.timeslot')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.unit')),
            ],
            options={
                'unique_together': {('room', 'time_slot')},
            },
        ),
    ]
