# Generated by Django 6.0.2 on 2026-02-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0003_timetableentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2')], help_text='Optional: Semester if the course is semester-specific', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=1, help_text='The academic year this course belongs to'),
        ),
    ]
