# Generated by Django 6.0.2 on 2026-02-24 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0004_course_semester_course_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1, help_text='Semester in which this unit is offered'),
        ),
        migrations.AddField(
            model_name='unit',
            name='students_count',
            field=models.PositiveIntegerField(default=50, help_text='Approximate number of students'),
        ),
        migrations.AddField(
            model_name='unit',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=1, help_text='Academic year this unit is taught in'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='timetabling.course'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='duration_hours',
            field=models.PositiveIntegerField(default=2, help_text='Duration per session (hours)'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='lecturer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('code', 'course', 'year', 'semester')},
        ),
    ]
