# Generated by Django 6.0.2 on 2026-02-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0005_unit_semester_unit_students_count_unit_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name_plural': 'Units'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.AlterField(
            model_name='unit',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=1, help_text='Year in which this unit is taught'),
        ),
    ]
