# Generated by Django 6.0.2 on 2026-03-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0006_alter_course_options_alter_unit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
