# Generated by Django 6.0.2 on 2026-03-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0007_alter_unit_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='unit',
            name='courses',
            field=models.ManyToManyField(related_name='units', to='timetabling.course'),
        ),
        migrations.RemoveField(
            model_name='unit',
            name='course',
        ),
    ]
