# Generated by Django 6.0.2 on 2026-03-01 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0008_alter_unit_unique_together_unit_courses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissedClassReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the missed class')),
                ('reason', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.timetableentry')),
            ],
        ),
        migrations.CreateModel(
            name='MakeupSlotRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_days', models.CharField(help_text='e.g. Monday, Wednesday', max_length=100)),
                ('preferred_times', models.CharField(help_text='e.g. Morning, Afternoon', max_length=100)),
                ('duration_hours', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('missed_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_request', to='timetabling.missedclassreport')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('lecturer', models.ForeignKey(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.timeslot')),
            ],
            options={
                'unique_together': {('lecturer', 'time_slot')},
            },
        ),
    ]
