# Generated by Django 6.0.2 on 2026-03-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Set to True when the admin explicitly shares the timetable'),
        ),
    ]
