# Generated by Django 6.0.2 on 2026-03-10 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0011_timetableentry_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeupslotrequest',
            name='allocated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makeupslotrequest',
            name='allocated_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetabling.room'),
        ),
        migrations.AddField(
            model_name='makeupslotrequest',
            name='allocated_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetabling.timeslot'),
        ),
        migrations.AlterField(
            model_name='makeupslotrequest',
            name='preferred_times',
            field=models.CharField(blank=True, help_text='e.g. Morning, Afternoon', max_length=100, null=True),
        ),
    ]
